// TEMPORARY mock data for the Champion Dashboard MVP.
// Kept in a clearly named file (not inline in pages) so it can be swapped for
// real FastAPI responses (GET /api/champion/...) without touching the UI.

import type {
  ChampionNote,
  ChampionSettings,
  InterviewReviewDetail,
  Meeting,
  PracticeAssignment,
  StudentDetail,
} from './types';

export const MOCK_CHAMPION_ID = 'champion-001';

export const mockChampionSettings: ChampionSettings = {
  firstName: 'Maya',
  lastName: 'Robinson',
  displayName: 'Maya Robinson',
  email: 'maya.robinson@yournextsteps-us.org',
  phone: '(312) 555-0142',
  title: 'Champion',
  organization: 'Your Next Steps-US',
  expertiseAreas: ['College Prep', 'Scholarships', 'Business'],
  bio: 'Career readiness mentor helping first-generation students prepare for college, scholarships, and their first internships.',
  timezone: 'America/Chicago',
  profileImageUrl: null,
  calendlyUrl: 'https://calendly.com/maya-robinson-yns',
  availabilityNote:
    'Students can book time with me for interview prep, scholarship guidance, and career questions.',
  notifyCompletedInterviews: true,
  notifyStudentNotes: true,
  notifyScheduledMeetings: true,
  alertStudentsNeedingHelp: true,
};

// Full student records. Summary views derive their fields from these.
export const mockStudents: StudentDetail[] = [
  {
    id: 'stu-001',
    firstName: 'Jordan',
    lastName: 'Alvarez',
    email: 'jordan.alvarez@example.edu',
    phone: '(773) 555-0111',
    school: 'Lincoln Park High School',
    educationLevel: 'high_school',
    year: 'Senior',
    fieldPursuing: 'Computer Science',
    goalType: 'college',
    gpa: 3.8,
    resumeUploaded: true,
    resumeUrl: '#',
    resumeLastUpdated: '2026-06-28',
    assignedChampionName: 'Maya Robinson',
    latestScore: 88,
    readinessScore: 84,
    averageScore: 82,
    completedInterviews: 6,
    totalPracticeMinutes: 214,
    lastPracticeDate: '2026-07-09',
    lastInterviewDate: '2026-07-09',
    upcomingMeetingDate: '2026-07-15',
    status: 'excellent',
    scoreTrend: [
      { date: '2026-05-20', score: 68 },
      { date: '2026-06-02', score: 74 },
      { date: '2026-06-18', score: 79 },
      { date: '2026-06-30', score: 83 },
      { date: '2026-07-09', score: 88 },
    ],
    skills: [
      { skill: 'Communication', score: 88, status: 'strong', recommendation: 'Keep leading with clear, concise summaries.' },
      { skill: 'Confidence', score: 82, status: 'good', recommendation: 'Practice steady pacing to reduce filler words.' },
      { skill: 'Response Structure', score: 85, status: 'strong', recommendation: 'STAR structure is landing well — keep it up.' },
      { skill: 'Technical Knowledge', score: 79, status: 'good', recommendation: 'Review core CS fundamentals before college interviews.' },
      { skill: 'Problem Solving', score: 81, status: 'good', recommendation: 'Narrate your thought process out loud more.' },
      { skill: 'Professionalism', score: 90, status: 'strong', recommendation: 'Excellent presence and follow-through.' },
    ],
  },
  {
    id: 'stu-002',
    firstName: 'Priya',
    lastName: 'Nair',
    email: 'priya.nair@example.edu',
    phone: null,
    school: 'University of Illinois Chicago',
    educationLevel: 'college',
    year: 'Sophomore',
    fieldPursuing: 'Business Administration',
    goalType: 'internship',
    gpa: 3.5,
    resumeUploaded: true,
    resumeUrl: '#',
    resumeLastUpdated: '2026-07-01',
    assignedChampionName: 'Maya Robinson',
    latestScore: 76,
    readinessScore: 72,
    averageScore: 71,
    completedInterviews: 4,
    totalPracticeMinutes: 138,
    lastPracticeDate: '2026-07-07',
    lastInterviewDate: '2026-07-07',
    upcomingMeetingDate: null,
    status: 'on_track',
    scoreTrend: [
      { date: '2026-05-28', score: 60 },
      { date: '2026-06-10', score: 65 },
      { date: '2026-06-24', score: 70 },
      { date: '2026-07-07', score: 76 },
    ],
    skills: [
      { skill: 'Communication', score: 74, status: 'good', recommendation: 'Add specific examples to support your points.' },
      { skill: 'Confidence', score: 68, status: 'needs_practice', recommendation: 'Rehearse openings to start strong.' },
      { skill: 'Response Structure', score: 70, status: 'good', recommendation: 'Wrap answers with a clear result statement.' },
      { skill: 'Technical Knowledge', score: 72, status: 'good', recommendation: 'Prepare 2-3 business case examples.' },
      { skill: 'Problem Solving', score: 73, status: 'good', recommendation: 'Show trade-offs in your reasoning.' },
      { skill: 'Time Management', score: 66, status: 'needs_practice', recommendation: 'Keep answers under two minutes.' },
    ],
  },
  {
    id: 'stu-003',
    firstName: 'Marcus',
    lastName: 'Bell',
    email: 'marcus.bell@example.edu',
    phone: '(312) 555-0199',
    school: 'Malcolm X College',
    educationLevel: 'college',
    year: 'Freshman',
    fieldPursuing: 'Nursing',
    goalType: 'scholarship',
    gpa: 3.1,
    resumeUploaded: false,
    resumeUrl: null,
    resumeLastUpdated: null,
    assignedChampionName: 'Maya Robinson',
    latestScore: 54,
    readinessScore: 49,
    averageScore: 52,
    completedInterviews: 2,
    totalPracticeMinutes: 46,
    lastPracticeDate: '2026-06-20',
    lastInterviewDate: '2026-06-20',
    upcomingMeetingDate: '2026-07-14',
    status: 'needs_help',
    scoreTrend: [
      { date: '2026-06-05', score: 58 },
      { date: '2026-06-20', score: 54 },
    ],
    skills: [
      { skill: 'Communication', score: 55, status: 'needs_practice', recommendation: 'Slow down and answer the full question.' },
      { skill: 'Confidence', score: 48, status: 'needs_help', recommendation: 'Schedule a 1:1 confidence-building session.' },
      { skill: 'Response Structure', score: 50, status: 'needs_help', recommendation: 'Introduce the STAR method with a worksheet.' },
      { skill: 'Technical Knowledge', score: 60, status: 'needs_practice', recommendation: 'Review scholarship "why" statements.' },
      { skill: 'Problem Solving', score: 52, status: 'needs_practice', recommendation: 'Walk through one example step by step.' },
      { skill: 'Professionalism', score: 62, status: 'needs_practice', recommendation: 'Practice a strong, warm introduction.' },
    ],
  },
  {
    id: 'stu-004',
    firstName: 'Sofia',
    lastName: 'Chen',
    email: 'sofia.chen@example.edu',
    phone: null,
    school: 'Whitney Young High School',
    educationLevel: 'high_school',
    year: 'Junior',
    fieldPursuing: 'Undecided',
    goalType: 'college',
    gpa: 4.0,
    resumeUploaded: true,
    resumeUrl: '#',
    resumeLastUpdated: '2026-05-30',
    assignedChampionName: 'Maya Robinson',
    latestScore: 93,
    readinessScore: 91,
    averageScore: 90,
    completedInterviews: 8,
    totalPracticeMinutes: 302,
    lastPracticeDate: '2026-07-10',
    lastInterviewDate: '2026-07-10',
    upcomingMeetingDate: '2026-07-16',
    status: 'excellent',
    scoreTrend: [
      { date: '2026-05-10', score: 80 },
      { date: '2026-05-28', score: 84 },
      { date: '2026-06-15', score: 88 },
      { date: '2026-06-30', score: 90 },
      { date: '2026-07-10', score: 93 },
    ],
    skills: [
      { skill: 'Communication', score: 94, status: 'strong', recommendation: 'Outstanding clarity — mentor peers next.' },
      { skill: 'Confidence', score: 91, status: 'strong', recommendation: 'Confident and personable throughout.' },
      { skill: 'Response Structure', score: 92, status: 'strong', recommendation: 'Very well organized answers.' },
      { skill: 'Leadership', score: 89, status: 'strong', recommendation: 'Highlight leadership stories in essays too.' },
      { skill: 'Problem Solving', score: 88, status: 'strong', recommendation: 'Keep showing structured reasoning.' },
      { skill: 'Professionalism', score: 95, status: 'strong', recommendation: 'Exceptional poise.' },
    ],
  },
  {
    id: 'stu-005',
    firstName: 'Devon',
    lastName: 'Washington',
    email: 'devon.washington@example.edu',
    phone: '(708) 555-0170',
    school: 'City Colleges of Chicago',
    educationLevel: 'recent_grad',
    year: 'Recent Graduate',
    fieldPursuing: 'Information Technology',
    goalType: 'job',
    gpa: 3.3,
    resumeUploaded: true,
    resumeUrl: '#',
    resumeLastUpdated: '2026-06-12',
    assignedChampionName: 'Maya Robinson',
    latestScore: 71,
    readinessScore: 63,
    averageScore: 67,
    completedInterviews: 5,
    totalPracticeMinutes: 176,
    lastPracticeDate: '2026-06-24',
    lastInterviewDate: '2026-06-24',
    upcomingMeetingDate: null,
    status: 'watch',
    scoreTrend: [
      { date: '2026-05-15', score: 72 },
      { date: '2026-05-30', score: 75 },
      { date: '2026-06-12', score: 70 },
      { date: '2026-06-24', score: 71 },
    ],
    skills: [
      { skill: 'Communication', score: 70, status: 'good', recommendation: 'Tighten answers and reduce jargon.' },
      { skill: 'Confidence', score: 65, status: 'needs_practice', recommendation: 'Practice mock technical screens weekly.' },
      { skill: 'Technical Knowledge', score: 74, status: 'good', recommendation: 'Refresh networking and OS fundamentals.' },
      { skill: 'Problem Solving', score: 68, status: 'needs_practice', recommendation: 'Think aloud during troubleshooting prompts.' },
      { skill: 'Time Management', score: 62, status: 'needs_practice', recommendation: 'Budget time across multi-part questions.' },
      { skill: 'Professionalism', score: 78, status: 'good', recommendation: 'Strong, steady interview presence.' },
    ],
  },
  {
    id: 'stu-006',
    firstName: 'Amara',
    lastName: 'Okafor',
    email: 'amara.okafor@example.edu',
    phone: null,
    school: 'Northeastern Illinois University',
    educationLevel: 'college',
    year: 'Junior',
    fieldPursuing: 'Public Health',
    goalType: 'internship',
    gpa: 3.6,
    resumeUploaded: false,
    resumeUrl: null,
    resumeLastUpdated: null,
    assignedChampionName: 'Maya Robinson',
    latestScore: null,
    readinessScore: null,
    averageScore: null,
    completedInterviews: 0,
    totalPracticeMinutes: 0,
    lastPracticeDate: null,
    lastInterviewDate: null,
    upcomingMeetingDate: '2026-07-18',
    status: 'not_started',
    scoreTrend: [],
    skills: [],
  },
];

export const mockInterviewReviews: InterviewReviewDetail[] = [
  {
    id: 'int-1001',
    studentId: 'stu-001',
    studentName: 'Jordan Alvarez',
    interviewPurpose: 'college',
    questionMode: 'behavioral',
    date: '2026-07-09',
    score: 88,
    status: 'completed',
    reviewStatus: 'pending',
    questions: [
      'Tell me about a time you led a team through a challenge.',
      'Why do you want to study Computer Science?',
      'Describe a project you are proud of.',
    ],
    transcriptSummary:
      'Jordan gave structured answers using the STAR method, with concrete examples from a robotics club project and strong reflection on lessons learned.',
    feedbackSummary:
      'Confident, well-organized responses. Strongest area was communication; could add more measurable outcomes.',
    scoreBreakdown: [
      { label: 'Communication', score: 88 },
      { label: 'Structure', score: 85 },
      { label: 'Confidence', score: 82 },
      { label: 'Relevance', score: 90 },
    ],
    strengths: ['Clear STAR structure', 'Specific project examples', 'Reflective tone'],
    improvementAreas: ['Quantify outcomes', 'Reduce filler words'],
    recommendedNextPractice: 'Behavioral interview focused on measurable impact.',
    championReviewNotes: null,
  },
  {
    id: 'int-1002',
    studentId: 'stu-003',
    studentName: 'Marcus Bell',
    interviewPurpose: 'scholarship',
    questionMode: 'situational',
    date: '2026-06-20',
    score: 54,
    status: 'completed',
    reviewStatus: 'needs_follow_up',
    questions: [
      'Why do you deserve this scholarship?',
      'Describe a time you overcame a setback.',
    ],
    transcriptSummary:
      'Marcus answered briefly and drifted off-topic on the second question. Answers lacked structure and specific examples.',
    feedbackSummary:
      'Needs support building structured answers and confidence. Recommend a 1:1 and a STAR worksheet.',
    scoreBreakdown: [
      { label: 'Communication', score: 55 },
      { label: 'Structure', score: 50 },
      { label: 'Confidence', score: 48 },
      { label: 'Relevance', score: 58 },
    ],
    strengths: ['Authentic and sincere', 'Motivated to improve'],
    improvementAreas: ['Answer the full question', 'Use a clear beginning-middle-result', 'Build confidence'],
    recommendedNextPractice: 'Situational practice with STAR scaffolding + resume upload.',
    championReviewNotes: 'Scheduled a 1:1 for July 14 to work on structure.',
  },
  {
    id: 'int-1003',
    studentId: 'stu-004',
    studentName: 'Sofia Chen',
    interviewPurpose: 'college',
    questionMode: 'mixed',
    date: '2026-07-10',
    score: 93,
    status: 'completed',
    reviewStatus: 'reviewed',
    questions: [
      'Walk me through your extracurricular leadership.',
      'How do you handle competing deadlines?',
      'What impact do you want to make in college?',
    ],
    transcriptSummary:
      'Sofia delivered polished, well-structured answers with strong leadership examples and clear future goals.',
    feedbackSummary: 'Excellent across the board. Ready for top-tier college interviews.',
    scoreBreakdown: [
      { label: 'Communication', score: 94 },
      { label: 'Structure', score: 92 },
      { label: 'Confidence', score: 91 },
      { label: 'Relevance', score: 95 },
    ],
    strengths: ['Exceptional clarity', 'Strong leadership stories', 'Confident delivery'],
    improvementAreas: ['Occasionally over-explains'],
    recommendedNextPractice: 'Advanced mock with rapid follow-up questions.',
    championReviewNotes: 'Great progress — encouraged her to mentor peers.',
  },
  {
    id: 'int-1004',
    studentId: 'stu-002',
    studentName: 'Priya Nair',
    interviewPurpose: 'internship',
    questionMode: 'behavioral',
    date: '2026-07-07',
    score: 76,
    status: 'completed',
    reviewStatus: 'pending',
    questions: [
      'Tell me about a time you worked on a team.',
      'What is a business problem you find interesting?',
    ],
    transcriptSummary:
      'Priya gave solid answers but started slowly. Good content once warmed up; her closing statements could be stronger.',
    feedbackSummary: 'Solid foundation. Focus on strong openings and confident pacing.',
    scoreBreakdown: [
      { label: 'Communication', score: 74 },
      { label: 'Structure', score: 70 },
      { label: 'Confidence', score: 68 },
      { label: 'Relevance', score: 78 },
    ],
    strengths: ['Good examples', 'Clear motivation'],
    improvementAreas: ['Stronger openings', 'More confident pacing'],
    recommendedNextPractice: 'Behavioral practice focused on first 30 seconds.',
    championReviewNotes: null,
  },
  {
    id: 'int-1005',
    studentId: 'stu-005',
    studentName: 'Devon Washington',
    interviewPurpose: 'job',
    questionMode: 'technical',
    date: '2026-06-24',
    score: 71,
    status: 'completed',
    reviewStatus: 'pending',
    questions: [
      'Explain the difference between TCP and UDP.',
      'How would you troubleshoot a slow network?',
    ],
    transcriptSummary:
      'Devon showed good fundamentals but hesitated on troubleshooting steps and ran long on the first answer.',
    feedbackSummary: 'Decent technical base; work on thinking aloud and time management.',
    scoreBreakdown: [
      { label: 'Technical', score: 74 },
      { label: 'Structure', score: 68 },
      { label: 'Confidence', score: 65 },
      { label: 'Time Mgmt', score: 62 },
    ],
    strengths: ['Solid fundamentals', 'Professional presence'],
    improvementAreas: ['Think aloud', 'Manage time across parts'],
    recommendedNextPractice: 'Technical screen with a 3-minute-per-question limit.',
    championReviewNotes: null,
  },
];

export const mockNotes: ChampionNote[] = [
  {
    id: 'note-2001',
    studentId: 'stu-001',
    studentName: 'Jordan Alvarez',
    championName: 'Maya Robinson',
    content:
      'Great job improving your communication. For your next practice, focus on using more specific, measurable examples.',
    visibility: 'student_visible',
    category: 'interview_feedback',
    createdAt: '2026-07-09',
    updatedAt: null,
  },
  {
    id: 'note-2002',
    studentId: 'stu-003',
    studentName: 'Marcus Bell',
    championName: 'Maya Robinson',
    content:
      'Marcus is showing low confidence and hasn\'t uploaded a resume. Flagging for closer follow-up and a possible check-in with his advisor.',
    visibility: 'private',
    category: 'follow_up',
    createdAt: '2026-06-21',
    updatedAt: null,
  },
  {
    id: 'note-2003',
    studentId: 'stu-003',
    studentName: 'Marcus Bell',
    championName: 'Maya Robinson',
    content:
      'You showed up and gave it your best — that matters. Let\'s work together on structuring your answers using the STAR method.',
    visibility: 'student_visible',
    category: 'encouragement',
    createdAt: '2026-06-21',
    updatedAt: null,
  },
  {
    id: 'note-2004',
    studentId: 'stu-004',
    studentName: 'Sofia Chen',
    championName: 'Maya Robinson',
    content: 'Excellent readiness. Consider nominating for the peer mentor program.',
    visibility: 'private',
    category: 'general',
    createdAt: '2026-07-10',
    updatedAt: null,
  },
];

export const mockAssignments: PracticeAssignment[] = [
  {
    id: 'asg-3001',
    studentId: 'stu-002',
    studentName: 'Priya Nair',
    interviewPurpose: 'internship',
    questionMode: 'behavioral',
    focusSkill: 'Confidence',
    resumeBased: true,
    dueDate: '2026-07-16',
    instructions: 'Focus on strong openings. Record and review the first 30 seconds of each answer.',
    status: 'assigned',
    createdAt: '2026-07-08',
  },
  {
    id: 'asg-3002',
    studentId: 'stu-003',
    studentName: 'Marcus Bell',
    interviewPurpose: 'scholarship',
    questionMode: 'situational',
    focusSkill: 'Response Structure',
    resumeBased: false,
    dueDate: '2026-07-13',
    instructions: 'Complete two situational questions using the STAR worksheet provided.',
    status: 'overdue',
    createdAt: '2026-06-28',
  },
  {
    id: 'asg-3003',
    studentId: 'stu-005',
    studentName: 'Devon Washington',
    interviewPurpose: 'job',
    questionMode: 'technical',
    focusSkill: 'Time Management',
    resumeBased: true,
    dueDate: '2026-07-20',
    instructions: 'Technical screen with a 3-minute limit per question. Practice thinking aloud.',
    status: 'in_progress',
    createdAt: '2026-07-05',
  },
  {
    id: 'asg-3004',
    studentId: 'stu-001',
    studentName: 'Jordan Alvarez',
    interviewPurpose: 'college',
    questionMode: 'behavioral',
    focusSkill: 'Communication',
    resumeBased: false,
    dueDate: '2026-07-02',
    instructions: 'Add measurable outcomes to each STAR answer.',
    status: 'completed',
    createdAt: '2026-06-25',
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: 'mtg-4001',
    studentId: 'stu-003',
    studentName: 'Marcus Bell',
    title: 'Confidence & structure 1:1',
    meetingType: 'interview_prep',
    startTime: '2026-07-14T15:00:00',
    endTime: '2026-07-14T15:30:00',
    status: 'scheduled',
    meetingUrl: 'https://meet.example.com/marcus-1on1',
  },
  {
    id: 'mtg-4002',
    studentId: 'stu-001',
    studentName: 'Jordan Alvarez',
    title: 'College interview prep',
    meetingType: 'mock_interview',
    startTime: '2026-07-15T17:00:00',
    endTime: '2026-07-15T17:45:00',
    status: 'scheduled',
    meetingUrl: 'https://meet.example.com/jordan-college',
  },
  {
    id: 'mtg-4003',
    studentId: 'stu-004',
    studentName: 'Sofia Chen',
    title: 'Advanced mock interview',
    meetingType: 'mock_interview',
    startTime: '2026-07-16T16:00:00',
    endTime: '2026-07-16T16:45:00',
    status: 'scheduled',
    meetingUrl: null,
  },
  {
    id: 'mtg-4004',
    studentId: 'stu-006',
    studentName: 'Amara Okafor',
    title: 'Getting started & goal setting',
    meetingType: 'general',
    startTime: '2026-07-18T14:00:00',
    endTime: '2026-07-18T14:30:00',
    status: 'scheduled',
    meetingUrl: null,
  },
  {
    id: 'mtg-4005',
    studentId: 'stu-002',
    studentName: 'Priya Nair',
    title: 'Internship strategy check-in',
    meetingType: 'career_question',
    startTime: '2026-06-30T15:30:00',
    endTime: '2026-06-30T16:00:00',
    status: 'completed',
    meetingUrl: null,
  },
];
