export const MAJOR_OPTIONS = [
  'Accounting',
  'Actuarial Science',
  'Advertising',
  'Aerospace Engineering',
  'African American Studies',
  'Agricultural Business',
  'Agricultural Engineering',
  'Agricultural Science',
  'American Studies',
  'Animal Science',
  'Anthropology',
  'Applied Mathematics',
  'Architecture',
  'Art Education',
  'Art History',
  'Artificial Intelligence',
  'Asian Studies',
  'Astronomy',
  'Astrophysics',
  'Biochemistry',
  'Bioengineering',
  'Biology',
  'Biomedical Engineering',
  'Biophysics',
  'Biostatistics',
  'Business Administration',
  'Business Analytics',
  'Chemical Engineering',
  'Chemistry',
  'Child Development',
  'Civil Engineering',
  'Classics',
  'Cognitive Science',
  'Communication',
  'Community Health',
  'Comparative Literature',
  'Computer Engineering',
  'Computer Science',
  'Construction Management',
  'Criminal Justice',
  'Cybersecurity',
  'Dance',
  'Data Analytics',
  'Data Science',
  'Dental Hygiene',
  'Design',
  'Digital Media',
  'Economics',
  'Education',
  'Electrical Engineering',
  'Elementary Education',
  'Engineering',
  'Engineering Management',
  'English',
  'Entrepreneurship',
  'Environmental Engineering',
  'Environmental Science',
  'Environmental Studies',
  'Ethnic Studies',
  'Exercise Science',
  'Fashion Design',
  'Film and Media Studies',
  'Finance',
  'Fine Arts',
  'Food Science',
  'Forensic Science',
  'French',
  'Game Design',
  'Gender Studies',
  'Geography',
  'Geology',
  'Global Studies',
  'Graphic Design',
  'Health Administration',
  'Health Science',
  'History',
  'Hospitality Management',
  'Human Biology',
  'Human Resources',
  'Industrial Engineering',
  'Information Systems',
  'Information Technology',
  'International Business',
  'International Relations',
  'Journalism',
  'Kinesiology',
  'Linguistics',
  'Management',
  'Management Information Systems',
  'Marketing',
  'Materials Science',
  'Mathematics',
  'Mechanical Engineering',
  'Media Studies',
  'Microbiology',
  'Music',
  'Music Education',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Operations Management',
  'Philosophy',
  'Physics',
  'Political Science',
  'Pre-Dental',
  'Pre-Law',
  'Pre-Med',
  'Pre-Nursing',
  'Pre-Pharmacy',
  'Psychology',
  'Public Health',
  'Public Policy',
  'Real Estate',
  'Religious Studies',
  'Robotics',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Spanish',
  'Special Education',
  'Sports Management',
  'Statistics',
  'Supply Chain Management',
  'Theater',
  'Urban Planning',
  'Veterinary Science',
  'Visual Arts',
] as const;

export const FIELD_OPTIONS = [
  'Accounting',
  'Actuarial Science',
  'Advertising',
  'Aerospace',
  'Agriculture',
  'AI Research',
  'Architecture',
  'Arts and Culture',
  'Automotive',
  'Banking',
  'Biotechnology',
  'Brand Strategy',
  'Business Analytics',
  'Business Development',
  'Chemical Engineering',
  'Civil Engineering',
  'Clinical Research',
  'Cloud Computing',
  'Communications',
  'Consulting',
  'Corporate Finance',
  'Creative Direction',
  'Criminal Justice',
  'Cybersecurity',
  'Data Analytics',
  'Data Engineering',
  'Data Science',
  'Dentistry',
  'Design',
  'Digital Marketing',
  'Education',
  'Electrical Engineering',
  'Energy',
  'Engineering',
  'Entertainment',
  'Entrepreneurship',
  'Environmental Sustainability',
  'Event Management',
  'Fashion',
  'Film and Media',
  'Financial Planning',
  'FinTech',
  'Game Development',
  'Government',
  'Graphic Design',
  'Healthcare',
  'Healthcare Administration',
  'Hospitality',
  'Human Resources',
  'Industrial Engineering',
  'Information Technology',
  'Insurance',
  'Investment Banking',
  'Journalism',
  'Law',
  'Life Sciences',
  'Logistics',
  'Machine Learning',
  'Manufacturing',
  'Marketing',
  'Mechanical Engineering',
  'Medicine',
  'Mental Health',
  'Mobile Development',
  'Music',
  'Nonprofit',
  'Nursing',
  'Operations',
  'Pharmaceuticals',
  'Product Design',
  'Product Management',
  'Project Management',
  'Public Health',
  'Public Policy',
  'Public Relations',
  'Real Estate',
  'Research',
  'Retail',
  'Robotics',
  'Sales',
  'Social Impact',
  'Social Media',
  'Software Engineering',
  'Sports',
  'Strategy',
  'Supply Chain',
  'Teaching',
  'Technical Program Management',
  'UX Research',
  'UX/UI Design',
  'Venture Capital',
  'Veterinary Medicine',
  'Web Development',
] as const;

export const MAJOR_OR_FIELD_OPTIONS = Array.from(new Set([...MAJOR_OPTIONS, ...FIELD_OPTIONS])).sort();
